/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface GrowlPathUtilities : NSObject
{
}

+ (id)growlPrefPaneBundle;
+ (id)helperAppBundle;
+ (id)searchPathForDirectory:(int)fp8 inDomains:(int)fp12 mustBeWritable:(BOOL)fp16;
+ (id)searchPathForDirectory:(int)fp8 inDomains:(int)fp12;
+ (id)growlSupportDirectory;
+ (id)screenshotsDirectory;
+ (id)ticketsDirectory;
+ (id)nextScreenshotName;
+ (id)nextScreenshotNameInDirectory:(id)fp8;
+ (id)defaultSavePathForTicketWithApplicationName:(id)fp8;

@end

