/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface GrowlApplicationBridge : NSObject
{
}

+ (void)setGrowlDelegate:(id)fp8;
+ (id)growlDelegate;
+ (void)notifyWithTitle:(id)fp8 description:(id)fp12 notificationName:(id)fp16 iconData:(id)fp20 priority:(int)fp24 isSticky:(BOOL)fp28 clickContext:(id)fp32;
+ (void)notifyWithTitle:(id)fp8 description:(id)fp12 notificationName:(id)fp16 iconData:(id)fp20 priority:(int)fp24 isSticky:(BOOL)fp28 clickContext:(id)fp32 identifier:(id)fp36;
+ (void)notifyWithDictionary:(id)fp8;
+ (BOOL)isGrowlInstalled;
+ (BOOL)isGrowlRunning;
+ (void)displayInstallationPromptIfNeeded;
+ (BOOL)registerWithDictionary:(id)fp8;
+ (void)reregisterGrowlNotifications;
+ (void)setWillRegisterWhenGrowlIsReady:(BOOL)fp8;
+ (BOOL)willRegisterWhenGrowlIsReady;
+ (id)registrationDictionaryFromDelegate;
+ (id)registrationDictionaryFromBundle:(id)fp8;
+ (id)bestRegistrationDictionary;
+ (id)registrationDictionaryByFillingInDictionary:(id)fp8;
+ (id)registrationDictionaryByFillingInDictionary:(id)fp8 restrictToKeys:(id)fp12;
+ (id)notificationDictionaryByFillingInDictionary:(id)fp8;
+ (id)frameworkInfoDictionary;
+ (id)_applicationNameForGrowlSearchingRegistrationDictionary:(id)fp8;
+ (id)_applicationIconDataForGrowlSearchingRegistrationDictionary:(id)fp8;
+ (void)growlNotificationWasClicked:(id)fp8;
+ (void)growlNotificationTimedOut:(id)fp8;
+ (void)connectionDidDie:(id)fp8;
+ (id)growlProxy;
+ (void)_growlIsReady:(id)fp8;
+ (BOOL)_launchGrowlIfInstalledWithRegistrationDictionary:(id)fp8;
+ (BOOL)launchGrowlIfInstalled;

@end

