/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSTextFieldCell.h"

@interface HighlightableTextFieldCell : NSTextFieldCell
{
    int compat_backgroundStyle;
}

- (void)compat_setBackgroundStyle:(int)fp8;
- (void)drawWithFrame:(struct _NSRect)fp8 inView:(id)fp24;

@end

