/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSDictionary;

@interface MATrackingArea : NSObject <NSCopying, NSCoding>
{
    struct _NSRect _rect;
    unsigned int _options;
    id _owner;
    NSDictionary *_userInfo;
    struct _NSPoint _lastMovedPoint;
    BOOL _inside;
}

+ (void)initialize;
+ (void)checkMouseLocation:(id)fp8;
+ (void)addTrackingArea:(id)fp8 toView:(id)fp12;
+ (void)removeTrackingArea:(id)fp8 fromView:(id)fp12;
+ (id)trackingAreasForView:(id)fp8;
- (id)initWithRect:(struct _NSRect)fp8 options:(unsigned int)fp24 owner:(id)fp28 userInfo:(id)fp32;
- (void)dealloc;
- (struct _NSRect)rect;
- (void)setRect:(struct _NSRect)fp8;
- (unsigned int)options;
- (id)owner;
- (id)userInfo;
- (struct _NSPoint)_lastMovedPoint;
- (void)_setLastMovedPoint:(struct _NSPoint)fp8;
- (BOOL)_inside;
- (void)_setInside:(BOOL)fp8;
- (void)_setNotInside;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;

@end

