/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSFileManager.h"

@interface NSFileManager (SPAuthentication)
- (BOOL)currentUserOwnsPath:(id)fp8;
- (BOOL)_copyPathWithForcedAuthentication:(id)fp8 toPath:(id)fp12;
- (BOOL)copyPathWithAuthentication:(id)fp8 toPath:(id)fp12;
@end

