/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (Additions)
- (id)stringByRemovingCharactersInSet:(id)fp8 options:(unsigned int)fp12;
- (id)stringByReplacingCharactersInSet:(id)fp8 withString:(id)fp12 options:(unsigned int)fp16;
- (id)stringByRemovingCharactersInSet:(id)fp8;
- (id)stringByRemovingCharacter:(unsigned short)fp8;
- (id)stringWithRemovedSubstring:(id)fp8;
@end

