/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSWindow.h"

@interface NSWindow (liveFrame)
- (struct _NSRect)liveFrame;
- (struct _NSRect)convertLiveBaseRectToScreen:(struct _NSRect)fp8;
@end

