/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSView.h"

@interface RoundedCornersView : NSView
{
    float _cornerRadius;
}

- (id)initWithFrame:(struct _NSRect)fp8;
- (void)drawRect:(struct _NSRect)fp8;
- (float)cornerRadius;
- (void)setCornerRadius:(float)fp8;

@end

