/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSView.h"

@interface SPAboutView : NSView
{
    struct GuiCanvas *canvas;
}

- (id)initWithFrame:(struct _NSRect)fp8;
- (void)drawRect:(struct _NSRect)fp8;
- (BOOL)acceptsFirstResponder;
- (void)mouseUp:(id)fp8;
- (void)dealloc;

@end

