/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSApplication.h"

@interface SPApplication : NSApplication
{
}

- (void)processCrashReports;
- (void)terminate:(id)fp8;
- (void)doNothingAtAll:(id)fp8;
- (void)sendEvent:(id)fp8;

@end

