/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSWindow.h"

@class NSControl, NSNib, NSString, SPAutocompleteMenuCell;

@interface SPAutocompleteMenuWindow : NSWindow
{
    NSControl *parentControl;
    struct AutocompleteDelegate *_completionDelegate;
    struct SPACMWWrap cpp;
    struct _NSRect _offset;
    NSNib *cellViewNib;
    SPAutocompleteMenuCell *headerCell;
    SPAutocompleteMenuCell *standardCell;
    SPAutocompleteMenuCell *standardWithIdentifierCell;
    SPAutocompleteMenuCell *separatorCell;
    SPAutocompleteMenuCell *_selectedCell;
    // Error parsing type: {FastDelegate2<bool,const sp::String&,void>="m_Closure"{ClosurePtr<void (fastdelegate::detail::GenericClass::*)(bool, const sp::String&),void (*)(bool, const sp::String&),void (*)(bool, const sp::String&)>="m_pthis"^{GenericClass}"m_pFunction"{?="__pfn"^"__delta"i}}}, name: _completionMade
    BOOL _skipNextSuggestion;
    NSString *_originallyTypedString;
    BOOL _hasCompleted;
    BOOL _showAutomatically;
    BOOL _showManually;
}

- (id)originallyTypedString;
- (void)setOriginallyTypedString:(id)fp8;
- (void)setShowAutomatically:(BOOL)fp8;
- (void)setOffset:(struct _NSRect)fp8;
- (id)initWithContentRect:(struct _NSRect)fp8 styleMask:(unsigned int)fp24 backing:(unsigned int)fp28 defer:(BOOL)fp32;
- (void)dealloc;
- (void)moveToBeneathControlWithHeight:(float)fp8;
- (void)addToControlIfNeeded:(id)fp8;
- (void)showOn:(id)fp8;
- (void)reset;
- (void)hide;
- (void)cancel;
- (void)controlTextDidBeginEditing:(id)fp8;
- (void)controlTextDidChange:(id)fp8;
- (void)controlTextDidEndEditing:(id)fp8;
- (BOOL)control:(id)fp8 textView:(id)fp12 doCommandBySelector:(SEL)fp16;
- (id)trackingAreaForView:(id)fp8 completion:(const struct Completion *)fp12;
- (void)setCompletionMade:(struct FastDelegate2<bool, const sp::String&, void>)fp8;
- (void)setCompletionDelegate:(struct AutocompleteDelegate *)fp8;
- (void)setCompletions:(const struct Array<sp::AutocompleteDelegate::Completion, const sp::AutocompleteDelegate::Completion&, 64, true> *)fp8;
- (void)setSelectedCell:(id)fp8;
- (void)userSetSelectedCell:(id)fp8;
- (id)cellBefore:(id)fp8;
- (id)cellAfter:(id)fp8;
- (void)mouseEntered:(id)fp8;
- (void)mouseExited:(id)fp8;
- (void)mouseUp:(id)fp8;
- (void)moveUp:(id)fp8;
- (void)moveDown:(id)fp8;
- (id).cxx_construct;

@end

