/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSView.h"

@class NSTextField;

@interface SPAutocompleteMenuCell : NSView
{
    int _tag;
    BOOL _highlighted;
    // Error parsing type: {Completion="displayable"{String=""($_2215="t"*"_d"^{StrPtrStruct})}"identifier"{String=""($_2215="t"*"_d"^{StrPtrStruct})}"entry_type"i"show_identifier"B"command"{FastDelegate1<const sp::AutocompleteDelegate::Completion&,void>="m_Closure"{ClosurePtr<void (fastdelegate::detail::GenericClass::*)(const sp::AutocompleteDelegate::Completion&),void (*)(const sp::AutocompleteDelegate::Completion&),void (*)(const sp::AutocompleteDelegate::Completion&)>="m_pthis"^{GenericClass}"m_pFunction"{?="__pfn"^"__delta"i}}}}, name: _completion
    NSTextField *text;
    NSTextField *identifier;
}

- (void)drawRect:(struct _NSRect)fp8;
- (int)tag;
- (void)setTag:(int)fp8;
- (struct Completion)completion;
- (void)setCompletion:(struct Completion)fp8;
- (BOOL)isHighlighted;
- (void)setHighlighted:(BOOL)fp8;
- (BOOL)selectable;
- (id).cxx_construct;
- (void).cxx_destruct;

@end

