/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SPController : NSObject
{
}

+ (id)sharedController;
+ (id)allocWithZone:(struct _NSZone *)fp8;
+ (int)windowAtTopOfEvent:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)retain;
- (unsigned int)retainCount;
- (void)release;
- (id)autorelease;
- (void)setFeedbackRegardingButton:(id)fp8;
- (void)setFeedbackScreenshotButton:(id)fp8;
- (void)setFeedbackTitleCell:(id)fp8;
- (void)setFeedbackFreeText:(id)fp8;
- (void)closeFeedbackForm:(id)fp8;
- (void)sendFeedback:(id)fp8;
- (void)resetFeedbackForm;
- (void)processFeedback;
- (void)applicationDidFinishLaunching:(id)fp8;
- (BOOL)validateMenuItem:(id)fp8;
- (void)doAction:(id)fp8;
- (void)copy:(id)fp8;
- (void)paste:(id)fp8;
- (void)cut:(id)fp8;
- (void)selectAll:(id)fp8;
- (void)delete:(id)fp8;
- (void)mediaKeyEvent:(id)fp8;
- (void)getURI:(id)fp8 withReplyEvent:(id)fp12;
- (void)openLink:(id)fp8 userData:(id)fp12 error:(id *)fp16;
- (BOOL)application:(id)fp8 openFile:(id)fp12;
- (void)setupWindowAndViews;
- (BOOL)applicationShouldHandleReopen:(id)fp8 hasVisibleWindows:(BOOL)fp12;
- (void)setSchedulerTimer;
- (void)setWindowController:(struct WindowControllerOSX *)fp8;
- (struct WindowControllerOSX *)windowController;
- (void)startup;
- (id)applicationDockMenu:(id)fp8;
- (void)notificationDelivery:(id)fp8;
- (id)mainWindow;
- (id)aboutWindow;
- (id)feedbackWindow;
- (id)introWindow;
- (void)pasteboard:(id)fp8 provideDataForType:(id)fp12;
- (void)pasteboard:(id)fp8 provideDataForType:(id)fp12 flags:(unsigned int)fp16;
- (id)dragPasteboard;
- (void)setDragPasteboard:(id)fp8;
- (id)stringDataFromPasteboard:(id)fp8;
- (BOOL)isShuttingDown;
- (void)dealloc;
- (void)prepareForShutdown;
- (void)focusCurrentlyPlayingTrack;

@end

