/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSWindowController.h"

@class NSButton, NSComboBox, NSImageView, NSTextField;

@interface SPEditMetadataWindowController : NSWindowController
{
    id delegate;
    NSTextField *filepathField;
    NSTextField *nameLabel;
    NSTextField *nameField;
    NSTextField *artistLabel;
    NSTextField *artistField;
    NSTextField *albumArtistLabel;
    NSTextField *albumArtistField;
    NSTextField *albumLabel;
    NSTextField *albumField;
    NSTextField *genreLabel;
    NSComboBox *genreBox;
    NSTextField *trackNumberLabel;
    NSTextField *trackNumberField;
    NSTextField *discNumberLabel;
    NSTextField *discNumberField;
    NSTextField *yearLabel;
    NSTextField *yearField;
    NSTextField *copyrightLabel;
    NSTextField *copyrightField;
    NSTextField *composerLabel;
    NSTextField *composerField;
    NSTextField *commentsLabel;
    NSTextField *commentsField;
    NSButton *cancelButton;
    NSButton *applyButton;
    NSButton *previousButton;
    NSButton *nextButton;
    NSImageView *lockImage;
    // Error parsing type: ^{MetadataEditor=ii{Array<sp::MetadataEditor::TrackData,const sp::MetadataEditor::TrackData&,64,true>="_mem"^{TrackData}"_alloc"I"_count"I}[18{String=""($_2215="t"*"_d"^{StrPtrStruct})}][18B][18i]{Array<sp::MetadataParser*,sp::MetadataParser* const&,64,true>="_mem"^^{MetadataParser}"_alloc"I"_count"I}{FastDelegate2<bool,const sp::String&,void>="m_Closure"{ClosurePtr<void (fastdelegate::detail::GenericClass::*)(bool, const sp::String&),void (*)(bool, const sp::String&),void (*)(bool, const sp::String&)>="m_pthis"^{GenericClass}"m_pFunction"{?="__pfn"^"__delta"i}}}{FastDelegate0<void>="m_Closure"{ClosurePtr<void (fastdelegate::detail::GenericClass::*)(),void (*)(),void (*)()>="m_pthis"^{GenericClass}"m_pFunction"{?="__pfn"^"__delta"i}}}{String=""($_2215="t"*"_d"^{StrPtrStruct})}Bi}, name: _editor
    struct MetadataEditorWindowDelegate *_windowDelegate;
}

- (id)initWithEditor:(struct MetadataEditor *)fp8 delegate:(struct MetadataEditorWindowDelegate *)fp12;
- (void)windowDidLoad;
- (void)controlTextDidBeginEditing:(id)fp8;
- (void)controlTextDidChange:(id)fp8;
- (int)numberOfItemsInComboBox:(id)fp8;
- (id)comboBox:(id)fp8 objectValueForItemAtIndex:(int)fp12;
- (void)cancelAction:(id)fp8;
- (void)applyAction:(id)fp8;
- (void)nextAction:(id)fp8;
- (void)previousAction:(id)fp8;
- (void)windowWillClose:(id)fp8;
- (_Bool)commitChanges;
- (void)updateFieldsFromEditor;
- (void)updateEditorFromField;
- (void)updateButtons;

@end

