/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SPHelpers : NSObject
{
}

+ (const char *)fontFaceForIndex:(int)fp8;
+ (struct CGImage *)CGImageRefFromNSBitmapImageRep:(id)fp8;
+ (id)NSColorFromColor:(const unsigned int *)fp8;
+ (float)fontFaceHeightMultiplier;

@end

