/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSView.h"

@class MATrackingArea, NSButton, NSImageView;

@interface SPIntroView : NSView
{
    struct PestoWindow *_pesto;
    MATrackingArea *trackingArea;
    NSButton *closeButton;
    NSButton *showMeButton;
    NSImageView *footer;
}

- (void)updateShowButtonState:(id)fp8;
- (void)closeButtonAction:(id)fp8;
- (id)initWithFrame:(struct _NSRect)fp8;
- (void)setFrame:(struct _NSRect)fp8;
- (void)drawRect:(struct _NSRect)fp8;
- (struct Point)pointInPestoCoordinates:(id)fp8;
- (void)mouseDown:(id)fp8;
- (void)mouseUp:(id)fp8;
- (void)mouseEntered:(id)fp8;
- (void)mouseExited:(id)fp8;
- (void)mouseMoved:(id)fp8;
- (void)resetCursorRects;

@end

