/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@interface SPKeychain : NSObject
{
}

+ (BOOL)checkForExistanceOfKeychainItem:(id)fp8 forUsername:(id)fp12;
+ (BOOL)addKeychainItem:(id)fp8 forUsername:(id)fp12 withPassword:(id)fp16;
+ (BOOL)modifyKeychainItem:(id)fp8 forUsername:(id)fp12 withNewPassword:(id)fp16;
+ (BOOL)deleteKeychainItem:(id)fp8 forUsername:(id)fp12;
+ (id)getPasswordFromKeychainItem:(id)fp8 forUsername:(id)fp12;
+ (id)getPasswordFromSecKeychainItemRef:(struct OpaqueSecKeychainItemRef *)fp8;

@end

