/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSMenuItem.h"

@interface SPMenuItem : NSMenuItem
{
    BOOL _enabledState;
}

- (id)initWithTitle:(id)fp8 action:(SEL)fp12 keyEquivalent:(id)fp16;
- (BOOL)_enabledState;
- (void)_setEnabledState:(BOOL)fp8;

@end

