/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSMenu.h"

@interface SPMenu : NSMenu
{
    struct PopupMenuOSX *menu;
    SPMenu *parent;
    // Error parsing type: {FastDelegate1<unsigned int,void>="m_Closure"{ClosurePtr<void (fastdelegate::detail::GenericClass::*)(unsigned int),void (*)(unsigned int),void (*)(unsigned int)>="m_pthis"^{GenericClass}"m_pFunction"{?="__pfn"^"__delta"i}}}, name: on_select
}

+ (int)selectedPopupItem;
- (struct FastDelegate1<unsigned int, void>)selectItem;
- (void)setParent:(id)fp8;
- (id)initWithMenu:(struct PopupMenuOSX *)fp8 title:(id)fp12;
- (void)doAction:(id)fp8;
- (void)setCallback:(struct FastDelegate1<unsigned int, void>)fp8;
- (struct IPopupMenu *)menuHandle;
- (void)dealloc;
- (int)numberOfItemsInMenu:(id)fp8;
- (BOOL)menu:(id)fp8 updateItem:(id)fp12 atIndex:(int)fp16 shouldCancel:(BOOL)fp20;
- (BOOL)performKeyEquivalent:(id)fp8;
- (id).cxx_construct;

@end

