/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSProxy.h"

@class NSMutableArray;

@interface SPMultiObjectProxy : NSProxy
{
    NSMutableArray *objects;
}

- (id)initWithObjects:(id)fp8;
- (void)dealloc;
- (id)objects;
- (void)forwardInvocation:(id)fp8;
- (id)methodSignatureForSelector:(SEL)fp8;
- (BOOL)respondsToSelector:(SEL)fp8;

@end

