/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSWindowController.h"

@class NSButton, NSString, NSTextField, NSTextView;

@interface SPPurchasePasswordCheckWindowController : NSWindowController
{
    NSString *_username;
    _Bool _rememberMe;
    _Bool _result;
    struct UserPasswordVerifier *_passwordVerifier;
    NSTextField *headerLabel;
    NSTextField *descLabel;
    NSTextField *usernameLabel;
    NSTextField *usernameField;
    NSTextField *passwordLabel;
    NSTextField *passwordField;
    NSTextView *forgotView;
    NSButton *rememberMeField;
    NSButton *cancelButton;
    NSButton *verifyButton;
}

- (id)initWithPasswordVerifier:(const struct UserPasswordVerifier *)fp8:(id)fp12:(_Bool)fp16;
- (_Bool)result;
- (_Bool)rememberMe;
- (void)verifyAction:(id)fp8;
- (void)alertDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)cancelAction:(id)fp8;
- (void)setEnabledFields:(BOOL)fp8;
- (void)windowDidLoad;

@end

