/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSSearchField.h"

@interface SPSearchField : NSSearchField
{
    struct PlatformEditBox *box;
}

- (id)initWithFrame:(struct _NSRect)fp8;
- (BOOL)becomeFirstResponder;
- (void)textDidChange:(id)fp8;
- (BOOL)textShouldEndEditing:(id)fp8;
- (void)textDidEndEditing:(id)fp8;
- (struct PlatformEditBox *)platformEditBox;
- (void)setPlatformEditBox:(struct PlatformEditBox *)fp8;

@end

