/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSTextField.h"

@interface SPStretchableTextField : NSTextField
{
    BOOL textDidChange;
}

- (id)initWithFrame:(struct _NSRect)fp8;
- (void)textDidChange:(id)fp8;
- (void)cancelOperation:(id)fp8;
- (void)textDidEndEditing:(id)fp8;

@end

