/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSTextView.h"

@class MATrackingArea, NSColor, NSMutableAttributedString, NSString;

@interface SPTextView : NSTextView
{
    MATrackingArea *trackingArea;
    NSString *lastLink;
    NSColor *lastColor;
    struct _NSRange lastLinkRange;
    NSMutableAttributedString *unmodifiedString;
    struct _NSSize offset;
    struct Rect rect;
    struct String url_checker;
    // Error parsing type: ^{NativeTextAreaManagerOSX=^^?l{Rect="left"i"top"i"right"i"bottom"i}{Point="x"i"y"i}{Array<sp::AttributedTextOSX*,sp::AttributedTextOSX* const&,64,true>="_mem"^^{AttributedTextOSX}"_alloc"I"_count"I}@"NSView"{FastDelegate2<sp::NativeTextAreaManager::LinkNotifyType,const sp::String&,bool>="m_Closure"{ClosurePtr<bool (fastdelegate::detail::GenericClass::*)(sp::NativeTextAreaManager::LinkNotifyType, const sp::String&),bool (*)(sp::NativeTextAreaManager::LinkNotifyType, const sp::String&),bool (*)(sp::NativeTextAreaManager::LinkNotifyType, const sp::String&)>="m_pthis"^{GenericClass}"m_pFunction"{?="__pfn"^"__delta"i}}}}, name: manager
}

- (struct _NSSize)offset;
- (struct Rect)rect;
- (void)truncateIfNeeded;
- (void)setRect:(struct Rect)fp8;
- (id)unmodifiedString;
- (void)setUnmodifiedString:(id)fp8;
- (id)initWithFrame:(struct _NSRect)fp8;
- (void)setManager:(struct NativeTextAreaManagerOSX *)fp8;
- (BOOL)acceptsFirstMouse:(id)fp8;
- (BOOL)shouldDrawInsertionPoint;
- (void)dealloc;
- (void)removeFromSuperview;
- (BOOL)displaysLinkToolTips;
- (void)resetCursorRects;
- (void)mouseMoved:(id)fp8;
- (void)resetLinkAttributes;
- (id)menuForEvent:(id)fp8;
- (void)mouseUp:(id)fp8;
- (void)mouseDown:(id)fp8;
- (void)mouseDragged:(id)fp8;
- (void)mouseExited:(id)fp8;
- (void)mouseEntered:(id)fp8;
- (id).cxx_construct;
- (void).cxx_destruct;

@end

