/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSTextField.h"

@interface SPTextField : NSTextField
{
    struct GuiEditBox *box;
}

- (id)initWithFrame:(struct _NSRect)fp8;
- (BOOL)becomeFirstResponder;
- (void)textDidChange:(id)fp8;
- (void)textDidEndEditing:(id)fp8;
- (struct GuiEditBox *)guiEditBox;
- (void)setGuiEditBox:(struct GuiEditBox *)fp8;

@end

