/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSGrayFrame.h"

@interface SPThemeFrame : NSGrayFrame
{
}

- (void)drawRect:(struct _NSRect)fp8;
- (struct _NSSize)_topCornerSize;
- (struct _NSSize)_bottomCornerSize;
- (float)roundedCornerRadius;
- (id)contentFill;
- (float)contentAlpha;

@end

