/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject.h"

@class NSWindow, WebView;

@interface SPWebBrowserHelper : NSObject
{
    struct WebBrowserOSX *_browser;
    NSWindow *_external_links_window;
    WebView *_external_links_webview;
}

- (void)webView:(id)fp8 decidePolicyForNavigationAction:(id)fp12 request:(id)fp16 frame:(id)fp20 decisionListener:(id)fp24;
- (void)webView:(id)fp8 didFinishLoadForFrame:(id)fp12;
- (void)webView:(id)fp8 resource:(id)fp12 didReceiveResponse:(id)fp16 fromDataSource:(id)fp20;
- (void)progressEstimateChanged:(id)fp8;
- (void)progressStarted:(id)fp8;
- (id)webView:(id)fp8 contextMenuItemsForElement:(id)fp12 defaultMenuItems:(id)fp16;
- (unsigned int)webView:(id)fp8 dragDestinationActionMaskForDraggingInfo:(id)fp12;
- (id)webView:(id)fp8 createWebViewWithRequest:(id)fp12;
- (void)setBrowserInstance:(struct WebBrowserOSX *)fp8;
- (void)dealloc;
- (id)init;

@end

